apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sync-wave
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "-30"  
spec:
  destination:
    namespace: sync-wave
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: sync-wave
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}