---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: app-backend
  # annotations:
  #   argocd.argoproj.io/sync-wave: "-99"
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: app-backend
  template:
    metadata:
      labels:
        tier: app-backend
    spec:
      containers:
        - name: main
          image: nginx:latest
---
apiVersion: v1
kind: Service
metadata:
  name: app-backend
spec:
  selector:
    tier: app-backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: app-frontend
  # annotations:
  #   argocd.argoproj.io/sync-wave: "-50"
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: app-frontend
  template:
    metadata:
      labels:
        tier: app-frontend
    spec:
      containers:
        - name: main
          image: nginx:latest
---
apiVersion: v1
kind: Service
metadata:
  name: app-frontend
spec:
  selector:
    tier: app-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
