---
---
apiVersion: batch/v1
kind: Job
metadata:
  name: sql-upgrade
  annotations:
    argocd.argoproj.io/sync-wave: "-100" 
spec:
  template:
    spec:
      containers:
        - name: sql-upgrade
          image: alpine:latest
          command: ["sleep", "8"]
      restartPolicy: Never
---
apiVersion: batch/v1
kind: Job
metadata:
  name: maint-page-up
  annotations:
    argocd.argoproj.io/sync-wave: "-99" 
spec:
  template:
    spec:
      containers:
        - name: page-up
          image: alpine:latest
          command: ["sleep", "5"]
      restartPolicy: Never
  backoffLimit: 0
