apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend-app
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-99" 
spec:
  project: default
  source:
    repoURL: https://github.com/pramachandran04/argocd-demo.git
    targetRevision: HEAD
    path: backend-app
  destination:
    server: https://kubernetes.default.svc
    namespace: backend-app
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true