apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: master
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-100" 
spec:
  project: default
  source:
    repoURL: https://github.com/pramachandran04/argocd-demo.git
    targetRevision: HEAD
    path: helm-demo
    helm: 
      valueFiles: 
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: sync-wave
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true