---
apiVersion: batch/v1
kind: Job
metadata:
  name: sql-upgrade
spec:
  template:
    spec:
      containers:
        - name: sql-upgrade
          image: alpine:latest
          command: ["sleep", "8"]
      restartPolicy: Never