---
apiVersion: batch/v1
kind: Job
metadata:
  name: maint-page-up
spec:
  template:
    spec:
      containers:
        - name: page-up
          image: alpine:latest
          command: ["sleep", "10"]
      restartPolicy: Never
  backoffLimit: 0
