apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sql-upgrade
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-50" 
spec:
  project: default
  source:
    repoURL: https://github.com/pramachandran04/argocd-demo.git
    targetRevision: HEAD
    path: sql-upgrade
  destination:
    server: https://kubernetes.default.svc
    namespace: sql-upgrade
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true